# Generated by Django 5.2.5 on 2025-09-01 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='users/')),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('city2', models.CharField(blank=True, max_length=20)),
                ('years', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
