# Generated by Django 5.2.5 on 2025-09-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='id1',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
