# Generated by Django 5.2.5 on 2025-09-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id1',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/'),
        ),
    ]
