# Generated by Django 5.2.5 on 2025-09-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_id1_alter_users_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
