# Generated by Django 5.2.5 on 2025-09-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='more_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='users')),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
