# Generated by Django 5.2.5 on 2025-09-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_products',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
