# Generated by Django 5.2.5 on 2025-09-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.IntegerField(),
        ),
    ]
