# Generated by Django 5.2.5 on 2025-09-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_comment_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True)),
                ('user_id', models.IntegerField(blank=True)),
                ('city', models.CharField(blank=True)),
                ('district', models.CharField(blank=True)),
                ('street', models.CharField(blank=True)),
                ('alley', models.CharField(blank=True)),
                ('plaque', models.IntegerField(blank=True)),
                ('floor', models.IntegerField(blank=True)),
                ('unit', models.IntegerField(blank=True)),
                ('postal', models.IntegerField(blank=True)),
            ],
        ),
    ]
