# Generated by Django 5.2.5 on 2025-09-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='username',
            new_name='user_name',
        ),
    ]
