# Generated by Django 5.2.5 on 2025-09-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'درحال بررسی'), ('confirmed', 'تایید شده'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده')], default='pending', max_length=20),
        ),
    ]
