# Generated by Django 5.2.5 on 2025-09-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_remove_order_status_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
