# Generated by Django 5.2.5 on 2025-09-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_inline_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
