# Generated by Django 5.2.5 on 2025-09-02 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inline',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
