# Generated by Django 5.2.5 on 2025-09-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_inline_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inline',
            name='name2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
