# Generated by Django 5.2.5 on 2025-09-02 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_inline_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.DeleteModel(
            name='inline',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
