# Generated by Django 5.2.5 on 2025-09-02 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_product_name_delete_inline_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('property_1', models.CharField(blank=True, max_length=20)),
                ('property_2', models.CharField(blank=True, max_length=20)),
                ('property_3', models.CharField(blank=True, max_length=20)),
                ('property_4', models.CharField(blank=True, max_length=20)),
                ('property_5', models.CharField(blank=True, max_length=20)),
                ('property_6', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField()),
                ('star', models.IntegerField()),
                ('mojod', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('image_main', models.ImageField(upload_to='images/')),
                ('image_1', models.ImageField(upload_to='images/')),
                ('image_2', models.ImageField(upload_to='images/')),
                ('image_3', models.ImageField(upload_to='images/')),
                ('image_4', models.ImageField(upload_to='images/')),
                ('image_5', models.ImageField(upload_to='images/')),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
