# Generated by Django 5.2.5 on 2025-09-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_old',
            field=models.BooleanField(default=False),
        ),
    ]
