# Generated by Django 5.2.5 on 2025-09-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_address_alley_alter_address_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='address',
        ),
    ]
